USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE DATABASE IMAGE_ANALYSIS;
CREATE OR REPLACE SCHEMA  IMAGE_ANALYSIS.VEHICLE_DAMAGE;
CREATE OR REPLACE SCHEMA  IMAGE_ANALYSIS.PLATE_NUTRITION;


CREATE OR REPLACE WAREHOUSE IMAGE_AI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;







