USE ROLE ACCOUNTADMIN;
USE DATABASE IMAGE_ANALYSIS;
USE SCHEMA IMAGE_ANALYSIS.PLATE_NUTRITION;
USE WAREHOUSE IMAGE_AI_WH;

--Create stage
CREATE STAGE IF NOT EXISTS IMAGE_ANALYSIS.PLATE_NUTRITION.FOODPLATE_IMAGES_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stores uploaded vehicle damage images';

CREATE TABLE IF NOT EXISTS PLATE_NUTRITION_ASSESSMENTS
(
    ASSESSMENT_ID NUMBER AUTOINCREMENT,
    FILE_NAME VARCHAR,
    FILE_TYPE VARCHAR,
    FILE_SIZE_BYTES NUMBER,
    STAGE_RELATIVE_PATH VARCHAR,
    MEAL_TYPE VARCHAR,
    CUISINE_TYPE VARCHAR,
    IMAGE_QUALITY VARCHAR,
    FOOD_ITEM_COUNT NUMBER,
    FOOD_ITEMS VARIANT,
    TOTAL_CALORIES NUMBER,
    TOTAL_PROTEIN_GRAMS NUMBER,
    TOTAL_CARBOHYDRATES_GRAMS NUMBER,
    TOTAL_FAT_GRAMS NUMBER,
    TOTAL_FIBER_GRAMS NUMBER,
    OVERALL_ASSESSMENT VARCHAR,
    COMPLETE_AI_RESPONSE VARIANT,
    AI_MODEL VARCHAR,
    ANALYZED_BY VARCHAR DEFAULT CURRENT_USER(),
    ANALYZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);