USE ROLE ACCOUNTADMIN;
USE DATABASE IMAGE_ANALYSIS;
USE SCHEMA IMAGE_ANALYSIS.VEHICLE_DAMAGE;
USE WAREHOUSE IMAGE_AI_WH;

--Create stage
CREATE OR REPLACE STAGE IMAGE_ANALYSIS.VEHICLE_DAMAGE.VEHICLE_IMAGES_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stores uploaded vehicle damage images';


CREATE OR REPLACE TABLE IMAGE_ANALYSIS.VEHICLE_DAMAGE.VEHICLE_DAMAGE_ASSESSMENTS
(
    ASSESSMENT_ID          NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    FILE_NAME              VARCHAR,
    FILE_TYPE              VARCHAR,
    FILE_SIZE_BYTES        NUMBER,

    STAGE_RELATIVE_PATH    VARCHAR,
    STAGE_FULL_PATH        VARCHAR,

    VEHICLE_VIEW           VARCHAR,
    IMAGE_QUALITY          VARCHAR,
    VEHICLE_DESCRIPTION    VARCHAR,

    DAMAGE_DETECTED        BOOLEAN,
    DAMAGE_COUNT           NUMBER,
    OVERALL_SEVERITY       VARCHAR,

    DAMAGES                VARIANT,
    OVERALL_ASSESSMENT     VARCHAR,
    RECOMMENDED_ACTION     VARCHAR,

    COMPLETE_AI_RESPONSE   VARIANT,

    AI_MODEL               VARCHAR,
    ANALYZED_BY            VARCHAR DEFAULT CURRENT_USER(),
    ANALYZED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);