USE WAREHOUSE IMAGE_AI_WH;
USE DATABASE IMAGE_ANALYSIS;
USE SCHEMA IMAGE_ANALYSIS.PLATE_NUTRITION;

CREATE OR REPLACE TABLE IMAGE_ANALYSIS.PLATE_NUTRITION.DAILY_NUTRITION_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    USER_NAME VARCHAR DEFAULT CURRENT_USER(),
    LOG_DATE DATE DEFAULT CURRENT_DATE(),
    LOG_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),

    MEAL_TYPE VARCHAR,
    USER_NOTE VARCHAR,
    FILE_NAME VARCHAR,
    STAGE_RELATIVE_PATH VARCHAR,

    CUISINE_TYPE VARCHAR,
    IMAGE_QUALITY VARCHAR,
    FOOD_ITEM_COUNT NUMBER,
    FOOD_ITEMS VARIANT,

    TOTAL_CALORIES NUMBER(10,2),
    TOTAL_PROTEIN_GRAMS NUMBER(10,2),
    TOTAL_CARBOHYDRATES_GRAMS NUMBER(10,2),
    TOTAL_FAT_GRAMS NUMBER(10,2),
    TOTAL_FIBER_GRAMS NUMBER(10,2),

    OVERALL_ASSESSMENT VARCHAR,
    COMPLETE_AI_RESPONSE VARIANT,
    AI_MODEL VARCHAR
);